apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      run: go-hpa
  template:
    metadata:
      labels:
        run: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: bralves/go-hpa
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m